package generator

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	"github.com/brendanjcarlson/genv/parser"
)

func Generate(args *parser.Args) {
	kvs := parser.ParseFiles(args)

	vars := make(map[string]string)
	for _, v := range kvs {
		vars[v.Key] = expand(v.Value, vars)
		v.Value = vars[v.Key]
	}

	parts := strings.Split(args.Output, "/")
	path := strings.Join(parts[:len(parts)-1], "/")

	err := os.MkdirAll(path, os.ModePerm)
	if err != nil {
		log.Fatalf("Failed to create directory: %s", err)
	}

	if _, err = os.Stat(args.Output); err == nil {
		err = os.Remove(args.Output)
		if err != nil {
			log.Fatalf("Failed to remove old file: %s", err)
		}
	}

	f, err := os.Create(args.Output)
	if err != nil {
		log.Fatalf("Failed to create file: %s", err)
	}
	defer f.Close()

	w := new(bytes.Buffer)

	writeHeader(w, args)
	writeImports(w, kvs)
	for _, v := range kvs {
		writeVar(w, v)
	}

	if _, err = f.Write(w.Bytes()); err != nil {
		log.Fatalf("Failed to write to file: %s", err)
	}
}

func expand(s string, vars map[string]string) string {
	return os.Expand(s, func(key string) string {
		return vars[key]
	})
}

func code(w io.Writer, msg string) {
	_, err := w.Write([]byte(msg))
	if err != nil {
		log.Fatalf("Failed to write to file: %s", err)
	}
}

func writeHeader(w io.Writer, args *parser.Args) {
	code(w, fmt.Sprintf("package %s\n\n", args.Package))
	code(w, "// Code generated by genv. DO NOT EDIT.\n\n")
}

func writeImports(w io.Writer, kv map[string]*parser.KeyValue) {
	code(w, "import (\n")
	code(w, "\t\"os\"\n")
	code(w, "\t\"log\"\n")

	timeImported := false
	strconvImported := false
	errorsImported := false
	for _, v := range kv {
		switch v.Type {
		case parser.TIME_DURATION:
			if !timeImported {
				code(w, "\t\"time\"\n")
				timeImported = true
			}
		case parser.INT:
			if !strconvImported {
				code(w, "\t\"strconv\"\n")
				strconvImported = true
			}
		case parser.ERROR:
			if !errorsImported {
				code(w, "\t\"errors\"\n")
				errorsImported = true
			}
		}
	}

	code(w, ")\n")
}

func varName(k string) string {
	s := strings.Split(strings.ToLower(k), "_")
	for i, w := range s {
		if i == 0 {
			continue
		}
		s[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(s, "")
}

func funcName(k string) string {
	s := strings.Split(strings.ToLower(k), "_")
	for i, w := range s {
		s[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(s, "")
}

func writeVar(w io.Writer, kv *parser.KeyValue) {
	k := kv.Key
	v := varName(k)
	f := funcName(k)
	t := kv.Type

	var l string
	switch t {
	case parser.INT8:
		l = prepInt8Var(k, v, f, t)
	case parser.INT16:
		l = prepInt16Var(k, v, f, t)
	case parser.INT32:
		l = prepInt32Var(k, v, f, t)
	case parser.INT64:
		l = prepInt64Var(k, v, f, t)
	case parser.UINT8:
		l = prepUint8Var(k, v, f, t)
	case parser.UINT16:
		l = prepUint16Var(k, v, f, t)
	case parser.UINT32:
		l = prepUint32Var(k, v, f, t)
	case parser.UINT64:
		l = prepUint64Var(k, v, f, t)
	case parser.INT:
		l = prepIntVar(k, v, f, t)
	case parser.UINT:
		l = prepUintVar(k, v, f, t)
	case parser.RUNE:
		l = prepRuneVar(k, v, f, t)
	case parser.BYTE:
		l = prepByteVar(k, v, f, t)
	case parser.BYTE_SLICE:
		l = prepByteSliceVar(k, v, f, t)
	case parser.FLOAT32:
		l = prepFloat32Var(k, v, f, t)
	case parser.FLOAT64:
		l = prepFloat64Var(k, v, f, t)
	case parser.COMPLEX64:
		l = prepComplex64Var(k, v, f, t)
	case parser.COMPLEX128:
		l = prepComplex128Var(k, v, f, t)
	case parser.BOOL:
		l = prepBoolVar(k, v, f, t)
	case parser.STRING:
		l = prepStringVar(k, v, f, t)
	case parser.ERROR:
		l = prepErrorVar(k, v, f, t)
	case parser.TIME_DURATION:
		l = prepTimeDurationVar(k, v, f, t)
	default:
		log.Fatalf("Unknown type: %s", t)
	}

	code(w, l)
}

func prepInt8Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseInt(x, 10, 8)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int8: ` + k + `")
        }
        ` + v + ` = int8(y)
    }
    return ` + v + `
}
`
}

func prepInt16Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseInt(x, 10, 16)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int16: ` + k + `")
        }
        ` + v + ` = int16(y)
    }
    return ` + v + `
}
`
}

func prepInt32Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseInt(x, 10, 32)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int32: ` + k + `")
        }
        ` + v + ` = int32(y)
    }
    return ` + v + `
}
`
}

func prepInt64Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseInt(x, 10, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int64: ` + k + `")
        }
        ` + v + ` = int64(y)
    }
    return ` + v + `
}
`
}

func prepUint8Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseUint(x, 10, 8)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint8: ` + k + `")
        }
        ` + v + ` = uint8(y)
    }
    return ` + v + `
}
`
}

func prepUint16Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseUint(x, 10, 16)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint16: ` + k + `")
        }
        ` + v + ` = uint16(y)
    }
    return ` + v + `
}
`
}

func prepUint32Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseUint(x, 10, 32)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint32: ` + k + `")
        }
        ` + v + ` = uint32(y)
    }
    return ` + v + `
}
`
}

func prepUint64Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseUint(x, 10, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint64: ` + k + `")
        }
        ` + v + ` = uint64(y)
    }
    return ` + v + `
}
`
}

func prepIntVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.Atoi(x)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int: ` + k + `")
        }
        ` + v + ` = y
    }
    return ` + v + `
}
`
}

func prepUintVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseUint(x, 10, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint: ` + k + `")
        }
        ` + v + ` = uint(y)
    }
    return ` + v + `
}
`
}

func prepRuneVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        ` + v + ` = rune([]byte(x)[0])
    }
    return ` + v + `
}
`
}

func prepByteVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        ` + v + ` = []byte(x)[0]
    }
    return ` + v + `
}
`
}

func prepByteSliceVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == nil {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        ` + v + ` = []byte(x)
    }
    return ` + v + `
}
`
}

func prepFloat32Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseFloat(x, 32)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to float32: ` + k + `")
        }
        ` + v + ` = float32(y)
    }
    return ` + v + `
}
`
}

func prepFloat64Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseFloat(x, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to float64: ` + k + `")
        }
        ` + v + ` = float64(y)
    }
    return ` + v + `
}
`
}

func prepComplex64Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseComplex(x, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to complex64: ` + k + `")
        }
        ` + v + ` = complex64(y)
    }
    return ` + v + `
}
`
}

func prepComplex128Var(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseComplex(x, 128)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to complex128: ` + k + `")
        }
        ` + v + ` = complex128(y)
    }
    return ` + v + `
}
`
}

func prepBoolVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == false {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := strconv.ParseBool(x)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to bool: ` + k + `")
        }
        ` + v + ` = y
    }
    return ` + v + `
}
`
}

func prepStringVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == "" {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        ` + v + ` = x
    }
    return ` + v + `
}
`
}

func prepErrorVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == nil {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        ` + v + ` = errors.New(x)
    }
    return ` + v + `
}
`
}

func prepTimeDurationVar(k, v, f, t string) string {
	return `
var ` + v + ` ` + t + `

func ` + f + `() ` + t + ` {
    if ` + v + ` == 0 {
        x, exists := os.LookupEnv("` + k + `")
        if !exists {
            log.Fatalf("Failed to find environment variable: ` + k + `")
        }
        y, err := time.ParseDuration(x)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to time.Duration: ` + k + `")
        }
        ` + v + ` = y
    }
    return ` + v + `
}
`
}
