package env

// Code generated by genv. DO NOT EDIT.

import (
	"os"
	"log"
	"strconv"
	"time"
	"errors"
)

var aUint16 uint16

func AUint16() uint16 {
    if aUint16 == 0 {
        x, exists := os.LookupEnv("A_UINT_16")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_UINT_16")
        }
        y, err := strconv.ParseUint(x, 10, 16)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint16: A_UINT_16")
        }
        aUint16 = uint16(y)
    }
    return aUint16
}

var anInt32 int32

func AnInt32() int32 {
    if anInt32 == 0 {
        x, exists := os.LookupEnv("AN_INT_32")
        if !exists {
            log.Fatalf("Failed to find environment variable: AN_INT_32")
        }
        y, err := strconv.ParseInt(x, 10, 32)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int32: AN_INT_32")
        }
        anInt32 = int32(y)
    }
    return anInt32
}

var anInt16 int16

func AnInt16() int16 {
    if anInt16 == 0 {
        x, exists := os.LookupEnv("AN_INT_16")
        if !exists {
            log.Fatalf("Failed to find environment variable: AN_INT_16")
        }
        y, err := strconv.ParseInt(x, 10, 16)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int16: AN_INT_16")
        }
        anInt16 = int16(y)
    }
    return anInt16
}

var aUint32 uint32

func AUint32() uint32 {
    if aUint32 == 0 {
        x, exists := os.LookupEnv("A_UINT_32")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_UINT_32")
        }
        y, err := strconv.ParseUint(x, 10, 32)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint32: A_UINT_32")
        }
        aUint32 = uint32(y)
    }
    return aUint32
}

var aUint64 uint64

func AUint64() uint64 {
    if aUint64 == 0 {
        x, exists := os.LookupEnv("A_UINT_64")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_UINT_64")
        }
        y, err := strconv.ParseUint(x, 10, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint64: A_UINT_64")
        }
        aUint64 = uint64(y)
    }
    return aUint64
}

var aUint uint

func AUint() uint {
    if aUint == 0 {
        x, exists := os.LookupEnv("A_UINT")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_UINT")
        }
        y, err := strconv.ParseUint(x, 10, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint: A_UINT")
        }
        aUint = uint(y)
    }
    return aUint
}

var aByte byte

func AByte() byte {
    if aByte == 0 {
        x, exists := os.LookupEnv("A_BYTE")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_BYTE")
        }
        aByte = []byte(x)[0]
    }
    return aByte
}

var aByteSlice []byte

func AByteSlice() []byte {
    if aByteSlice == nil {
        x, exists := os.LookupEnv("A_BYTE_SLICE")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_BYTE_SLICE")
        }
        aByteSlice = []byte(x)
    }
    return aByteSlice
}

var aFloat64 float64

func AFloat64() float64 {
    if aFloat64 == 0 {
        x, exists := os.LookupEnv("A_FLOAT_64")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_FLOAT_64")
        }
        y, err := strconv.ParseFloat(x, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to float64: A_FLOAT_64")
        }
        aFloat64 = float64(y)
    }
    return aFloat64
}

var anInt8 int8

func AnInt8() int8 {
    if anInt8 == 0 {
        x, exists := os.LookupEnv("AN_INT_8")
        if !exists {
            log.Fatalf("Failed to find environment variable: AN_INT_8")
        }
        y, err := strconv.ParseInt(x, 10, 8)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int8: AN_INT_8")
        }
        anInt8 = int8(y)
    }
    return anInt8
}

var aBool bool

func ABool() bool {
    if aBool == false {
        x, exists := os.LookupEnv("A_BOOL")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_BOOL")
        }
        y, err := strconv.ParseBool(x)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to bool: A_BOOL")
        }
        aBool = y
    }
    return aBool
}

var anError error

func AnError() error {
    if anError == nil {
        x, exists := os.LookupEnv("AN_ERROR")
        if !exists {
            log.Fatalf("Failed to find environment variable: AN_ERROR")
        }
        anError = errors.New(x)
    }
    return anError
}

var aComplex64 complex64

func AComplex64() complex64 {
    if aComplex64 == 0 {
        x, exists := os.LookupEnv("A_COMPLEX_64")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_COMPLEX_64")
        }
        y, err := strconv.ParseComplex(x, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to complex64: A_COMPLEX_64")
        }
        aComplex64 = complex64(y)
    }
    return aComplex64
}

var anInt int

func AnInt() int {
    if anInt == 0 {
        x, exists := os.LookupEnv("AN_INT")
        if !exists {
            log.Fatalf("Failed to find environment variable: AN_INT")
        }
        y, err := strconv.Atoi(x)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int: AN_INT")
        }
        anInt = y
    }
    return anInt
}

var aFloat32 float32

func AFloat32() float32 {
    if aFloat32 == 0 {
        x, exists := os.LookupEnv("A_FLOAT_32")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_FLOAT_32")
        }
        y, err := strconv.ParseFloat(x, 32)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to float32: A_FLOAT_32")
        }
        aFloat32 = float32(y)
    }
    return aFloat32
}

var aComplex128 complex128

func AComplex128() complex128 {
    if aComplex128 == 0 {
        x, exists := os.LookupEnv("A_COMPLEX_128")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_COMPLEX_128")
        }
        y, err := strconv.ParseComplex(x, 128)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to complex128: A_COMPLEX_128")
        }
        aComplex128 = complex128(y)
    }
    return aComplex128
}

var aString string

func AString() string {
    if aString == "" {
        x, exists := os.LookupEnv("A_STRING")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_STRING")
        }
        aString = x
    }
    return aString
}

var aUint8 uint8

func AUint8() uint8 {
    if aUint8 == 0 {
        x, exists := os.LookupEnv("A_UINT_8")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_UINT_8")
        }
        y, err := strconv.ParseUint(x, 10, 8)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to uint8: A_UINT_8")
        }
        aUint8 = uint8(y)
    }
    return aUint8
}

var aRune rune

func ARune() rune {
    if aRune == 0 {
        x, exists := os.LookupEnv("A_RUNE")
        if !exists {
            log.Fatalf("Failed to find environment variable: A_RUNE")
        }
        aRune = rune([]byte(x)[0])
    }
    return aRune
}

    var aDuration time.Duration

    func ADuration() time.Duration {
        if aDuration == 0 {
            x, exists := os.LookupEnv("A_DURATION")
            if !exists {
                log.Fatalf("Failed to find environment variable: A_DURATION")
            }
            y, err := time.ParseDuration(x)
            if err != nil {
                log.Fatalf("Failed to convert environment variable to time.Duration: A_DURATION")
            }
            aDuration = y
        }
        return aDuration
    }
    
var anInt64 int64

func AnInt64() int64 {
    if anInt64 == 0 {
        x, exists := os.LookupEnv("AN_INT_64")
        if !exists {
            log.Fatalf("Failed to find environment variable: AN_INT_64")
        }
        y, err := strconv.ParseInt(x, 10, 64)
        if err != nil {
            log.Fatalf("Failed to convert environment variable to int64: AN_INT_64")
        }
        anInt64 = int64(y)
    }
    return anInt64
}
